#!/usr/bin/env python3

import json
import sys
import os

class App(object):
    def __init__(self):
        self.match = None

    def activate(self, index):
        if  not self.match:
            return
            
        sys.stdout.write('"Close"\n')
        sys.stdout.flush()


    def github_latest_release(self, query):
        search = query.split()


# github_latest_release() {
#     local username=$1
#     local repository=$2

#     # Get the latest release information from GitHub API using jq
#     local latest_release=$(curl -s "https://api.github.com/repos/$username/$repository/releases/latest" | jq -r '.assets[0].browser_download_url')

#     # Use wget to download the deb file
#     wget $latest_release
# }

# github_latest_release "$@"
